### ISSUE TITLE
/usr/bin/sort: invalid option -- 'D'

### ISSUE THREAD

**Issue by andresriancho** [cyberark/SkyArk#1]
This is most likely an invalid bug report because I'm running the tool in Linux, but...

```
[+] Discovered 32 privileged entities in the scanned AWS environment
/usr/bin/sort: invalid option -- 'D'
Try '/usr/bin/sort --help' for more information.
[+] Exported the results to: 
"/home/andres/tools/SkyArk/AWStealth\AWStealth - Results.csv"

/usr/bin/sort: invalid option -- 'D'
Try '/usr/bin/sort --help' for more information.
-> AWStealth discovered 0 privileged entities
Cannot index into a null array.
At /home/andres/tools/SkyArk/AWStealth/AWStealth.ps1:809 char:5
+     $awsAccount = (([string]$allPrivivlgedEntities[0]).Split(":"))[4]
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : NullArray
 
[+] Check the final report: 
"/home/andres/tools/SkyArk/AWStealth\AWStealth - Final Report.txt"



PS /home/andres/tools/SkyArk/AWStealth> 
```

`AWStealth - Results.csv` is empty.

And the report text says:

```
AWStealth scanned:
2195 Users
2160 Groups
4443 Roles
90 Managed Policies
7418 Inline Policies

...

Total number of the most privileged AWS entities: 0
Total number of AWS Shadow Admins: 0

Number of privileged Users: 0
Number of privileged Groups: 0
Number of privileged Roles: 0
```

I know there are various shadow admins. So it seems that the `sort` issue broke reporting.

Enumerating all those users, groups, roles, etc. took a while and everything seemed to work well. Sadly... that final sort broke everything.

**Comment by andresriancho** [comment]
https://github.com/PowerShell/PowerShell/issues/4005

**Comment by andresriancho** [comment]
Trying fix at https://github.com/PowerShell/PowerShell/issues/567#issuecomment-208657337 with `Set-PSAliases`

**Comment by Hechtov** [comment]
Glad to hear you are trying using the tool from a Linux machine, indeed PowerShell for Linux might be tricky.. I haven't tried it by myself yet.
I can advise to run the tool from a Windows machine until we fix this issue. Please keep us update if you still have trouble.
Thanks

**Comment by andresriancho** [comment]
The fix I posted in the previous comment worked perfectly!

**Comment by Hechtov** [comment]
OK sounds awesome, thanks for the help.
I don't have any experience with PowerShell on Linux, so to be sure, is the
bug\fix in the Linux PowerShell engine side? or can we fix it from within
SkyArk code?
You referred to a new function "Set-PSAliases", should it be added to the
SkyArk code?

**Comment by andresriancho** [comment]
Well, I was able to run the script in linux after using `Set-PSAliases`.

IMHO if you want people to use this tool in linux, you can:
 * Change the code to detect if linux is in use and run `Set-PSAliases` before the script
 * Change the code to detect if linux is in use and stop if the user has not manually run `Set-PSAliases`

**Comment by Hechtov** [comment]
Thank you @andresriancho and sorry about the delay.
We are planning to address this issue in the future.

**Comment by Hechtov** [comment]
Sorry it took me long time to get to it. I fixed this issue.
Simply changed the "sort" command to "sort-object", it should work now because there are no conflicts with the local Linux Aliases names.
