### ISSUE TITLE
Enhancement - Python for Linux and Mac

### ISSUE THREAD

**Issue by etendards** [cyberark/SkyArk#2]
please port this to Linux and MacOS so we can use this very awesome code!  Please and Thanks!

**Comment by Hechtov** [comment]
Thanks @etendards for opening this issue, as we see it, it's a feature request and not a bug.
SkyArk\AWStealth is currently in PowerShell but we agree that there is a great value in implementing the scan also in Python.
We will close this issue for now, this idea of adding a Python version for the scan was added to our future features list.
BTW, you are welcome to try the new scanning module - AzureStealth for Azure, and share more feedback.
Thanks.
