### ISSUE TITLE
AWStealth does not support assumed roles

### ISSUE THREAD

**Issue by brandond** [cyberark/SkyArk#7]
The script seems to assume that you're using user credentials. I user a master profile that I then reference from other profiles via AssumeRole:

```ini
[profile OtherAccount-audit]
format = json
region = us-west-2
source_profile = MasterProfile
role_arn = arn:aws:iam::111111111111:role/InfoSec-audit
external_id = xxx
```

The code here fails due to assuming the profile's credentials are associated with an IAM user, not a role:
https://github.com/cyberark/SkyArk/blob/650138a02278f98449f99430964ac43c81f032ba/AWStealth/AWStealth.ps1#L140
```
Get-IAMUser : Must specify userName when calling with non-User credentials
At C:\...\AWStealth.ps1:140 char:20
+     $currentUser = Get-IAMUser
+                    ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Amazon.PowerShe...etIAMUserCmdlet:GetIAMUserCmdlet) [Get-IAMUser], InvalidOperationException
    + FullyQualifiedErrorId : Amazon.IdentityManagement.AmazonIdentityManagementServiceException,Amazon.PowerShell.Cmdlets.IAM.GetIAMUserCmdlet
```

I'm not sure if it's related, but the attempt to delete a temporary profile also fails here:
https://github.com/cyberark/SkyArk/blob/650138a02278f98449f99430964ac43c81f032ba/AWStealth/AWStealth.ps1#L1185
```
Remove-AWSCredentialProfile : The CredentialProfile 'AWStealthProfile' does not exist.
At C:\...\AWStealth.ps1:1185 char:5
+     Remove-AWSCredentialProfile -ProfileName $tempProfile -force
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Amazon.PowerShe...alProfileCmdlet:RemoveAWSCredentialProfileCmdlet) [Remove-AWSCredentialProfile], ArgumentException
    + FullyQualifiedErrorId : ArgumentException,Amazon.PowerShell.Common.RemoveAWSCredentialProfileCmdlet
```

**Comment by Hechtov** [comment]
Hi @brandond, that true, currently the scan intended to work with AWS Access Key ID and Secret Key of an IAM user.
Please try to use regular access key of a IAM ser and not a role, and update me.
We are considering adding support to run the scan with role and local profile, in the future. But currently just use regular IAM user credentials (with read only over the IAM).

**Comment by brandond** [comment]
I have 30+ accounts to run this on. I don't have an IAM user, but since I'm on the InfoSec team I do have an audit role that I can assume. It's hardly feasible for me to go out and ask all our teams to create a user for me just so I can run a one-off script when I already have a role.

**Comment by brandond** [comment]
I will note that this is part of a CyberArk professional services engagement that also sees us running a DNA Scan against our on-prem environment.

**Comment by Hechtov** [comment]
@brandond how are you? we have just updated AWStealth scan to support Assumed Roles with SessionTokens. As part of initiating of the scan, it will prompt you and ask you for a session token (it's an optional parameter).
Please have a try. In my tests it works nicely, you can reopen the ticket otherwise.
Thanks.
